
#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3'
networks:
  pbc_network:
    external: true

services:
  app:
    container_name: sp
    image: go_pbc
    env_file: .env
    tty: true
    volumes:
      - .:/app
    ports:
      - 4001:4001
    networks:
      - pbc_network
    command: >
      ash -c "air"

  # nginx:
  #     container_name: nginx
  #     build: ./nginx
  #     volumes:
  #         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     ports:
  #         - 80:80
  #     restart: always
  #     depends_on:
  #         - app
  #     networks:
  #         - pbc_network

  orion:
    labels:
      org.fiware: 'tutorial'
    image: fiware/orion
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - pbc_network
    ports:
      - 1026:1026 # localhost:1026
    command: -dbhost mongo-db -logLevel DEBUG -noCache
    healthcheck:
      test: curl --fail -s http://orion:${ORION_PORT}/version || exit 1
      interval: 5s

  # Databases
  mongo-db:
    labels:
      org.fiware: 'tutorial'
    image: mongo
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - 27017
    ports:
      - 27017:27017 # localhost:27017 # localhost:27017
    networks:
      - pbc_network
    volumes:
      - ./orion/mongo-db:/data
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $host/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
      interval: 5s
