
#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3'
networks:
  pbc_network:
    external: true

services:
  app:
    container_name: sp
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - 4001:4001
    networks:
      - pbc_network
    command: >
      ash -c "air"

  nginx:
      container_name: nginx
      build: ./nginx
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
          - 80:80
      restart: always
      depends_on:
          - app
      networks:
          - pbc_network
