/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateRegistrationRequest struct {
	Description string `json:"description"`
	DataProvided *interface{} `json:"dataProvided"`
	Provider *interface{} `json:"provider"`
}
