/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateAttributeDataRequest struct {
	Value float64 `json:"value"`
	Metadata *interface{} `json:"metadata"`
}
