/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Options3 string

// List of Options3
const (
	KEY_VALUES_Options3 Options3 = "keyValues"
	UPSERT_Options3 Options3 = "upsert"
)
