/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Options10 string

// List of Options10
const (
	APPEND_Options10 Options10 = "append"
	KEY_VALUES_Options10 Options10 = "keyValues"
)
