/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LocationValue struct {
	Value PointValue `json:"value"`
	Type  string     `json:"type"`
}

type PointValue struct {
	Type        string `json:"type"`
	Coordinates []int  `json:"coordinates"`
}

type MetaStringValue struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}

type MetaValues struct {
	Type  string   `json:"type"`
	Value []string `json:"value"`
}

type CreateEntityRequest struct {
	Type_     string           `json:"type"`
	Id        string           `json:"id"`
	Point     *LocationValue   `json:"point"`
	MetaOne   *MetaStringValue `json:"meta_one"`
	MetaTwo   *MetaStringValue `json:"meta_two"`
	MetaThree *MetaStringValue `json:"meta_three"`
}

// "humidity": {
//     "value": 60
//   },
//   "location": {
//     "value": "41.3763726, 2.1864475",
//     "type": "geo:point",
//     "metadata": {
//       "crs": {
//         "value": "WGS84"
//       }
//     }
//   }

// type CreateEntityRequest struct {
// 	Type_ string `json:"type"`
// 	Id string `json:"id"`
// 	Temperature *interface{} `json:"temperature"`
// 	Humidity *interface{} `json:"humidity"`
// 	Location *interface{} `json:"location"`
// }
