/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ReplaceAllEntityAttributesRequest struct {
	Temperature *interface{} `json:"temperature"`
	SeatNumber *interface{} `json:"seatNumber"`
}
