/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Options string

// List of Options
const (
	COUNT_Options Options = "count"
	KEY_VALUES_Options Options = "keyValues"
	VALUES_Options Options = "values"
	UNIQUE_Options Options = "unique"
)
