/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RetrieveApiResourcesResponse struct {
	// URL which points to the entities resource
	EntitiesUrl string `json:"entities_url"`
	// URL which points to the types resource
	TypesUrl string `json:"types_url"`
	// URL which points to the subscriptions resource
	SubscriptionsUrl string `json:"subscriptions_url"`
	// URL which points to the registrations resource
	RegistrationsUrl string `json:"registrations_url"`
}
