/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StringValue struct {
	Value string `json:"value"`
	Type  string `json:"type"`
}

type LocationValue struct {
	Value string `json:"value"`
	Type  string `json:"type"`
}

type CreateEntityRequest struct {
	Type_       string       `json:"type"`
	Id          string       `json:"id"`
	Temperature *StringValue `json:"temperature"`
}

// "humidity": {
//     "value": 60
//   },
//   "location": {
//     "value": "41.3763726, 2.1864475",
//     "type": "geo:point",
//     "metadata": {
//       "crs": {
//         "value": "WGS84"
//       }
//     }
//   }

// type CreateEntityRequest struct {
// 	Type_ string `json:"type"`
// 	Id string `json:"id"`
// 	Temperature *interface{} `json:"temperature"`
// 	Humidity *interface{} `json:"humidity"`
// 	Location *interface{} `json:"location"`
// }
