/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Options20 string

// List of Options20
const (
	COUNT_Options20 Options20 = "count"
	VALUES_Options20 Options20 = "values"
)
