/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListEntitiesResponse struct {
	Type_ string          `json:"type"`
	Id    string          `json:"id"`
	Point LocationValue   `json:"point"`
	Meta  MetaStringValue `json:"meta"`
}
