/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetAttributeValueResponse struct {
	Address string `json:"address"`
	ZipCode int32 `json:"zipCode"`
	City string `json:"city"`
	Country string `json:"country"`
}
