/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateSubscriptionRequest struct {
	Description string `json:"description"`
	Subject *interface{} `json:"subject"`
	Notification *interface{} `json:"notification"`
	Expires string `json:"expires"`
	Throttling int32 `json:"throttling"`
}
