/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Options6 string

// List of Options6
const (
	KEY_VALUES_Options6 Options6 = "keyValues"
	VALUES_Options6 Options6 = "values"
	UNIQUE_Options6 Options6 = "unique"
)
